"""Declarative base and shared column conventions for all ORM models.

Every model in Phase 3 inherits from Base so a single MetaData object backs
Alembic autogenerate.
"""

from datetime import datetime

from sqlalchemy import BigInteger, DateTime, Identity, MetaData, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# Predictable constraint names, so Alembic can autogenerate reversible migrations.
# Without these, PostgreSQL invents names that migrations cannot reliably drop.
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Shared declarative base. All timestamps are timezone-aware and stored in UTC."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


def bigint_pk() -> Mapped[int]:
    """BIGINT GENERATED BY DEFAULT AS IDENTITY primary key.

    PostgreSQL generates the value, so keys are never computed in Python
    and never derived from MAX(id) + 1.
    """
    return mapped_column(BigInteger, Identity(always=False), primary_key=True)


def utc_now_column(**kwargs) -> Mapped[datetime]:
    """TIMESTAMP WITH TIME ZONE column defaulting to the database's UTC clock."""
    return mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),  # PostgreSQL now() is timezone-aware
        **kwargs,
    )


class CreatedAtMixin:
    """Adds created_at only. Used by append-only event tables, which are never updated."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )


class TimestampMixin:
    """Adds created_at / updated_at to a model.

    Defaults are generated by PostgreSQL, so timestamps stay consistent no matter
    which process writes the row.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )
