"""phase2 baseline empty schema

Revision ID: 6bce95798004
Revises: 
Create Date: 2026-09-19 16:38:55.172697
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6bce95798004'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
