"""phase3 core models

Revision ID: de2d51593dcd
Revises: 6bce95798004
Create Date: 2026-09-19 16:47:37.755000
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'de2d51593dcd'
down_revision: Union[str, None] = '6bce95798004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Sequences backing the visitor_code / staff_code column defaults.
    # Created first because the table DEFAULTs call nextval() on them.
    # nextval() is atomic, so concurrent inserts can never receive the same code.
    op.execute("CREATE SEQUENCE IF NOT EXISTS visitor_code_seq START WITH 1 INCREMENT BY 1")
    op.execute("CREATE SEQUENCE IF NOT EXISTS staff_code_seq START WITH 1 INCREMENT BY 1")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameras',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('camera_id', sa.String(length=64), nullable=False),
    sa.Column('camera_name', sa.String(length=128), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('rtsp_url', sa.String(length=512), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'OFFLINE'"), nullable=False),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('last_frame_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ONLINE', 'OFFLINE', 'ERROR', 'DISABLED')", name=op.f('ck_cameras_status_valid')),
    sa.CheckConstraint('fps IS NULL OR fps >= 0', name=op.f('ck_cameras_fps_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cameras')),
    sa.UniqueConstraint('camera_id', name=op.f('uq_cameras_camera_id'))
    )
    op.create_index('ix_cameras_enabled', 'cameras', ['enabled'], unique=False)
    op.create_index('ix_cameras_status', 'cameras', ['status'], unique=False)
    op.create_table('staff',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('staff_code', sa.String(length=16), server_default=sa.text("('STAFF-'::text || lpad((nextval('staff_code_seq'::regclass))::text, 3, '0'::text))"), nullable=False),
    sa.Column('staff_name', sa.String(length=128), nullable=False),
    sa.Column('employee_code', sa.String(length=64), nullable=True),
    sa.Column('department', sa.String(length=128), nullable=True),
    sa.Column('face_embedding', sa.LargeBinary(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff')),
    sa.UniqueConstraint('employee_code', name=op.f('uq_staff_employee_code')),
    sa.UniqueConstraint('staff_code', name=op.f('uq_staff_staff_code'))
    )
    op.create_index('ix_staff_active', 'staff', ['active'], unique=False)
    op.create_index('ix_staff_department', 'staff', ['department'], unique=False)
    op.create_table('camera_events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('camera_id', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("event_type IN ('ONLINE', 'OFFLINE', 'ERROR', 'RECOVERED')", name=op.f('ck_camera_events_event_type_valid')),
    sa.CheckConstraint('fps IS NULL OR fps >= 0', name=op.f('ck_camera_events_fps_non_negative')),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], name=op.f('fk_camera_events_camera_id_cameras'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_camera_events'))
    )
    op.create_index(op.f('ix_camera_events_camera_id'), 'camera_events', ['camera_id'], unique=False)
    op.create_index('ix_camera_events_camera_id_event_time', 'camera_events', ['camera_id', 'event_time'], unique=False)
    op.create_index('ix_camera_events_event_time', 'camera_events', ['event_time'], unique=False)
    op.create_index('ix_camera_events_event_type', 'camera_events', ['event_type'], unique=False)
    op.create_table('seats',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('seat_id', sa.String(length=32), nullable=False),
    sa.Column('hall_id', sa.String(length=64), server_default=sa.text("'MAIN'"), nullable=False),
    sa.Column('seat_label', sa.String(length=64), nullable=True),
    sa.Column('row_number', sa.Integer(), nullable=True),
    sa.Column('column_number', sa.Integer(), nullable=True),
    sa.Column('camera_id', sa.BigInteger(), nullable=True),
    sa.Column('polygon_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("polygon_points IS NULL OR jsonb_typeof(polygon_points) = 'array'", name=op.f('ck_seats_polygon_points_is_array')),
    sa.CheckConstraint('column_number IS NULL OR column_number >= 0', name=op.f('ck_seats_column_number_non_negative')),
    sa.CheckConstraint('row_number IS NULL OR row_number >= 0', name=op.f('ck_seats_row_number_non_negative')),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], name=op.f('fk_seats_camera_id_cameras'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seats')),
    sa.UniqueConstraint('hall_id', 'seat_id', name='hall_id_seat_id')
    )
    op.create_index(op.f('ix_seats_camera_id'), 'seats', ['camera_id'], unique=False)
    op.create_index('ix_seats_enabled', 'seats', ['enabled'], unique=False)
    op.create_index('ix_seats_hall_id', 'seats', ['hall_id'], unique=False)
    op.create_index('ix_seats_seat_id', 'seats', ['seat_id'], unique=False)
    op.create_table('staff_attendance',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('staff_id', sa.BigInteger(), nullable=False),
    sa.Column('camera_id', sa.BigInteger(), nullable=True),
    sa.Column('entry_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'PRESENT'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'PRESENT' AND exit_time IS NULL) OR (status = 'EXITED' AND exit_time IS NOT NULL)", name=op.f('ck_staff_attendance_exit_time_matches_status')),
    sa.CheckConstraint("status IN ('PRESENT', 'EXITED')", name=op.f('ck_staff_attendance_status_valid')),
    sa.CheckConstraint('exit_time IS NULL OR exit_time >= entry_time', name=op.f('ck_staff_attendance_exit_after_entry')),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], name=op.f('fk_staff_attendance_camera_id_cameras'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], name=op.f('fk_staff_attendance_staff_id_staff'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff_attendance'))
    )
    op.create_index(op.f('ix_staff_attendance_camera_id'), 'staff_attendance', ['camera_id'], unique=False)
    op.create_index('ix_staff_attendance_entry_time', 'staff_attendance', ['entry_time'], unique=False)
    op.create_index(op.f('ix_staff_attendance_staff_id'), 'staff_attendance', ['staff_id'], unique=False)
    op.create_index('ix_staff_attendance_status', 'staff_attendance', ['status'], unique=False)
    op.create_index('uq_staff_attendance_active', 'staff_attendance', ['staff_id'], unique=True, postgresql_where=sa.text("status = 'PRESENT'"))
    op.create_table('visitors',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('visitor_code', sa.String(length=16), server_default=sa.text("('VIS-'::text || lpad((nextval('visitor_code_seq'::regclass))::text, 6, '0'::text))"), nullable=False),
    sa.Column('tracking_id', sa.BigInteger(), nullable=True),
    sa.Column('camera_id', sa.BigInteger(), nullable=True),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('current_seat_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'INSIDE', 'EXITED')", name=op.f('ck_visitors_status_valid')),
    sa.CheckConstraint('exit_time IS NULL OR entry_time IS NULL OR exit_time >= entry_time', name=op.f('ck_visitors_exit_after_entry')),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], name=op.f('fk_visitors_camera_id_cameras'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['current_seat_id'], ['seats.id'], name=op.f('fk_visitors_current_seat_id_seats'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visitors')),
    sa.UniqueConstraint('visitor_code', name=op.f('uq_visitors_visitor_code'))
    )
    op.create_index('ix_visitors_active_status', 'visitors', ['status'], unique=False, postgresql_where=sa.text("status <> 'EXITED'"))
    op.create_index(op.f('ix_visitors_camera_id'), 'visitors', ['camera_id'], unique=False)
    op.create_index(op.f('ix_visitors_current_seat_id'), 'visitors', ['current_seat_id'], unique=False)
    op.create_index('ix_visitors_entry_time', 'visitors', ['entry_time'], unique=False)
    op.create_index('ix_visitors_last_seen', 'visitors', ['last_seen'], unique=False)
    op.create_index('ix_visitors_status', 'visitors', ['status'], unique=False)
    op.create_table('seat_occupancy',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('seat_id', sa.BigInteger(), nullable=False),
    sa.Column('camera_id', sa.BigInteger(), nullable=True),
    sa.Column('person_type', sa.String(length=16), nullable=False),
    sa.Column('visitor_id', sa.BigInteger(), nullable=True),
    sa.Column('staff_id', sa.BigInteger(), nullable=True),
    sa.Column('occupied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'OCCUPIED'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(person_type = 'VISITOR' AND visitor_id IS NOT NULL AND staff_id IS NULL) OR (person_type = 'STAFF' AND staff_id IS NOT NULL AND visitor_id IS NULL)", name=op.f('ck_seat_occupancy_occupant_matches_person_type')),
    sa.CheckConstraint("(status = 'OCCUPIED' AND released_at IS NULL) OR (status = 'RELEASED' AND released_at IS NOT NULL)", name=op.f('ck_seat_occupancy_released_at_matches_status')),
    sa.CheckConstraint("person_type IN ('VISITOR', 'STAFF')", name=op.f('ck_seat_occupancy_person_type_valid')),
    sa.CheckConstraint("status IN ('OCCUPIED', 'RELEASED')", name=op.f('ck_seat_occupancy_status_valid')),
    sa.CheckConstraint('duration_seconds IS NULL OR duration_seconds >= 0', name=op.f('ck_seat_occupancy_duration_non_negative')),
    sa.CheckConstraint('released_at IS NULL OR released_at >= occupied_at', name=op.f('ck_seat_occupancy_released_after_occupied')),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], name=op.f('fk_seat_occupancy_camera_id_cameras'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], name=op.f('fk_seat_occupancy_seat_id_seats'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], name=op.f('fk_seat_occupancy_staff_id_staff'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.id'], name=op.f('fk_seat_occupancy_visitor_id_visitors'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seat_occupancy'))
    )
    op.create_index(op.f('ix_seat_occupancy_camera_id'), 'seat_occupancy', ['camera_id'], unique=False)
    op.create_index('ix_seat_occupancy_occupied_at', 'seat_occupancy', ['occupied_at'], unique=False)
    op.create_index('ix_seat_occupancy_person_type', 'seat_occupancy', ['person_type'], unique=False)
    op.create_index(op.f('ix_seat_occupancy_seat_id'), 'seat_occupancy', ['seat_id'], unique=False)
    op.create_index(op.f('ix_seat_occupancy_staff_id'), 'seat_occupancy', ['staff_id'], unique=False)
    op.create_index('ix_seat_occupancy_status', 'seat_occupancy', ['status'], unique=False)
    op.create_index(op.f('ix_seat_occupancy_visitor_id'), 'seat_occupancy', ['visitor_id'], unique=False)
    op.create_index('uq_seat_occupancy_active', 'seat_occupancy', ['seat_id'], unique=True, postgresql_where=sa.text("status = 'OCCUPIED'"))
    op.create_table('visitor_events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('visitor_id', sa.BigInteger(), nullable=True),
    sa.Column('camera_id', sa.BigInteger(), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tracking_id', sa.BigInteger(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("event_type IN ('DETECTED', 'ENTERED', 'EXITED', 'SEAT_ASSIGNED', 'SEAT_RELEASED', 'LOST')", name=op.f('ck_visitor_events_event_type_valid')),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], name=op.f('fk_visitor_events_camera_id_cameras'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.id'], name=op.f('fk_visitor_events_visitor_id_visitors'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visitor_events'))
    )
    op.create_index(op.f('ix_visitor_events_camera_id'), 'visitor_events', ['camera_id'], unique=False)
    op.create_index('ix_visitor_events_event_time', 'visitor_events', ['event_time'], unique=False)
    op.create_index('ix_visitor_events_event_type', 'visitor_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_visitor_events_visitor_id'), 'visitor_events', ['visitor_id'], unique=False)
    op.create_index('ix_visitor_events_visitor_id_event_time', 'visitor_events', ['visitor_id', 'event_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_visitor_events_visitor_id_event_time', table_name='visitor_events')
    op.drop_index(op.f('ix_visitor_events_visitor_id'), table_name='visitor_events')
    op.drop_index('ix_visitor_events_event_type', table_name='visitor_events')
    op.drop_index('ix_visitor_events_event_time', table_name='visitor_events')
    op.drop_index(op.f('ix_visitor_events_camera_id'), table_name='visitor_events')
    op.drop_table('visitor_events')
    op.drop_index('uq_seat_occupancy_active', table_name='seat_occupancy', postgresql_where=sa.text("status = 'OCCUPIED'"))
    op.drop_index(op.f('ix_seat_occupancy_visitor_id'), table_name='seat_occupancy')
    op.drop_index('ix_seat_occupancy_status', table_name='seat_occupancy')
    op.drop_index(op.f('ix_seat_occupancy_staff_id'), table_name='seat_occupancy')
    op.drop_index(op.f('ix_seat_occupancy_seat_id'), table_name='seat_occupancy')
    op.drop_index('ix_seat_occupancy_person_type', table_name='seat_occupancy')
    op.drop_index('ix_seat_occupancy_occupied_at', table_name='seat_occupancy')
    op.drop_index(op.f('ix_seat_occupancy_camera_id'), table_name='seat_occupancy')
    op.drop_table('seat_occupancy')
    op.drop_index('ix_visitors_status', table_name='visitors')
    op.drop_index('ix_visitors_last_seen', table_name='visitors')
    op.drop_index('ix_visitors_entry_time', table_name='visitors')
    op.drop_index(op.f('ix_visitors_current_seat_id'), table_name='visitors')
    op.drop_index(op.f('ix_visitors_camera_id'), table_name='visitors')
    op.drop_index('ix_visitors_active_status', table_name='visitors', postgresql_where=sa.text("status <> 'EXITED'"))
    op.drop_table('visitors')
    op.drop_index('uq_staff_attendance_active', table_name='staff_attendance', postgresql_where=sa.text("status = 'PRESENT'"))
    op.drop_index('ix_staff_attendance_status', table_name='staff_attendance')
    op.drop_index(op.f('ix_staff_attendance_staff_id'), table_name='staff_attendance')
    op.drop_index('ix_staff_attendance_entry_time', table_name='staff_attendance')
    op.drop_index(op.f('ix_staff_attendance_camera_id'), table_name='staff_attendance')
    op.drop_table('staff_attendance')
    op.drop_index('ix_seats_seat_id', table_name='seats')
    op.drop_index('ix_seats_hall_id', table_name='seats')
    op.drop_index('ix_seats_enabled', table_name='seats')
    op.drop_index(op.f('ix_seats_camera_id'), table_name='seats')
    op.drop_table('seats')
    op.drop_index('ix_camera_events_event_type', table_name='camera_events')
    op.drop_index('ix_camera_events_event_time', table_name='camera_events')
    op.drop_index('ix_camera_events_camera_id_event_time', table_name='camera_events')
    op.drop_index(op.f('ix_camera_events_camera_id'), table_name='camera_events')
    op.drop_table('camera_events')
    op.drop_index('ix_staff_department', table_name='staff')
    op.drop_index('ix_staff_active', table_name='staff')
    op.drop_table('staff')
    op.drop_index('ix_cameras_status', table_name='cameras')
    op.drop_index('ix_cameras_enabled', table_name='cameras')
    op.drop_table('cameras')
    # ### end Alembic commands ###

    # Sequences are dropped last: the tables whose DEFAULTs reference them are gone by now.
    op.execute("DROP SEQUENCE IF EXISTS staff_code_seq")
    op.execute("DROP SEQUENCE IF EXISTS visitor_code_seq")
